version: '3.4'

services:
  customdotnetcoreweb:
    image: ${DOCKER_REGISTRY-}customdotnetcoreweb
    build:
      context: .
      dockerfile: CustomDotNetCoreWeb/Dockerfile
    ports:
     - "8081:80"
    depends_on:
     - db

  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
        ACCEPT_EULA: "Y" 
        SA_PASSWORD: "1234"
    ports:
      - "1433:1433"
